version: "3.8"

services:
    rundapp-api:                    
        build: .
        ports:
        - "8000:8000"
        container_name: rundapp-api
        env_file: 
        - .env
        depends_on:
        - db   

    continuous-integration:
        container_name: rundapp-api-continuous-integration
        image: "rundapp/rundapp-api"
        env_file:
            - tests.env
        entrypoint: /app/continuous_integration/initiate_tests.sh
        depends_on:
            - test_db

    test_db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5444
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=rundapp-dev-test
        ports:
            - 5444:5444
        command: -p 5444

    db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=rundapp-dev
        ports:
            - 5432:5432